//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSpecialProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forum
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int Deleted { get; set; }
        public bool Active { get; set; }
        public bool Default { get; set; }
    }
}
