//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSpecialProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOnCart
    {
        public int ID { get; set; }
        public Nullable<int> QuantityOnCart { get; set; }
        public int IdCart { get; set; }
        public string Status { get; set; }
        public int IdProduct { get; set; }
        public string ProductName { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> IdOrder { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual ProductToSell ProductToSell { get; set; }
        public virtual Order Order { get; set; }
    }
}
